AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Documentation:
  Enabled: false
